import Head from 'next/head'
import Feed from 'components/Feed.js'
import MenuBar from 'components/MenuBar'
import Sidebar from 'components/Sidebar'

export default function Home() {
    return (
            <div>
                <Head>

                    <link rel="preconnect" href="https://fonts.googleapis.com"/>
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
                    <link href="https://fonts.googleapis.com/css2?family=Iceberg&family=Inter&family=Rubik:wght@300;400&display=swap" rel="stylesheet"/>

                    <title>SIEGE</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <main className="flex min-h-screen mx-auto">
                    {/*Componentes da página*/}
                    <MenuBar/>
                    <Feed/>
                    <Sidebar/>

                </main>

            </div>
            )
}